### ISSUE TITLE
Compare basic regriding functions

### ISSUE THREAD

**Issue by chengzhuzhang** [lee1043/XCDAT#8]

**Comment by pochedls** [comment]
@chengzhuzhang - I happened to be breaking everything up into tickets at the exact same time. Could we close this ticket (#9 is similar and has a few additional details)?

**Comment by lee1043** [comment]
Item merges to https://github.com/lee1043/XCDAT/issues/9

**Comment by chengzhuzhang** [comment]
Got it! Thanks!
